server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Serj-C/spring-cloudconfig
          search-paths:
            - station*
          repos:
            perf:
              pattern: '*/perf'
              uri: https://github.com/Serj-C/spring-cloudconfig-perf
              search-paths:
                - station*